import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import favicon from "../public/favicon.png"
import { Providers } from "@/components/Providers";
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { Providers1 } from './GlobalRedux/provider';
import { PersistGate } from 'redux-persist/integration/react'; 

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Domino\'s Pizza',

  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.png" type="image/x-icon" />
      </head>
      <body className={inter.className}>
        <Providers>
          <Providers1>
            <Navbar />
            {children}
            <Footer />
          </Providers1>
        </Providers>
      </body>
    </html>
  )
}
